config/routes.rb
Rails.application.routes.draw do

  get 'orders/add_product'

  get 'admin/permission'
  get 'admin/:id/edit' => 'admin#edit', :as => "admin_edit"
  patch 'admin/:id' => 'admin#update'
  put 'admin/:id' => 'admin#update'

  get 'orders/search_test'
  get 'orders/add_customer'

  resources :orders do
    collection do
      delete 'destroy_multiple'
      get 'search_action'
      get 'search_result'
      get 'sku_select'
    end
  end
  resources :delivery_agencies do
    collection do
      delete 'destroy_multiple'
    end
  end
  resources :business_groups do
    collection do
      delete 'destroy_multiple'
    end
  end
  resources :suppliers do
    collection do
      delete 'destroy_multiple'
    end
  end

  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }

  resources :products do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :customers do
      collection do
        delete 'destroy_multiple'
      end
    end

  devise_scope :user do
    root to: "devise/sessions#new"
  end

end

app/models/delivery_agency.rb
class DeliveryAgency < ActiveRecord::Base
end

app/controllers/delivery_agencies_controller.rb
class DeliveryAgenciesController < ApplicationController
  require 'will_paginate/array'

  before_action :set_delivery_agency, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /delivery_agencies
  # GET /delivery_agencies.json
  def index
    @delivery_agencies = DeliveryAgency.all
    @per_page = params[:per_page] || DeliveryAgency.per_page || 2
    @delivery_agencies = @delivery_agencies.paginate( :per_page => @per_page, :page => params[:page])
  end

  # GET /delivery_agencies/1
  # GET /delivery_agencies/1.json
  def show
  end

  # GET /delivery_agencies/new
  def new
    @delivery_agency = DeliveryAgency.new
  end

  # GET /delivery_agencies/1/edit
  def edit
  end

  # POST /delivery_agencies
  # POST /delivery_agencies.json
  def create
    @delivery_agency = DeliveryAgency.new(delivery_agency_params)

    respond_to do |format|
      if @delivery_agency.save
        format.html { redirect_to @delivery_agency, notice: 'Delivery agency was successfully created.' }
        format.json { render :show, status: :created, location: @delivery_agency }
      else
        format.html { render :new }
        format.json { render json: @delivery_agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /delivery_agencies/1
  # PATCH/PUT /delivery_agencies/1.json
  def update
    respond_to do |format|
      if @delivery_agency.update(delivery_agency_params)
        format.html { redirect_to @delivery_agency, notice: 'Delivery agency was successfully updated.' }
        format.json { render :show, status: :ok, location: @delivery_agency }
      else
        format.html { render :edit }
        format.json { render json: @delivery_agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /delivery_agencies/1
  # DELETE /delivery_agencies/1.json
  def destroy
    @delivery_agency.destroy
    respond_to do |format|
      format.html { redirect_to delivery_agencies_url, notice: 'Delivery agency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroy_multiple
    DeliveryAgency.destroy(params[:delivery_agencies])
    respond_to do |format|
      format.html {redirect_to delivery_agencies_url, notice: 'Delivery Agencies were successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_delivery_agency
      @delivery_agency = DeliveryAgency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def delivery_agency_params
      params.require(:delivery_agency).permit(:name, :email, :phone, :address)
    end
end

app/helpers/delivery_agencies_helper.rb
module DeliveryAgenciesHelper
end

app/views/delivery_agencies/_form.html.erb
<%= form_for(@delivery_agency) do |f| %>
  <% if @delivery_agency.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4><%= pluralize(@delivery_agency.errors.count, "error") %> prohibited this delivery agency from being saved:</h4>

      <ul>
      <% @delivery_agency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="stripe_error" class="alert alert-danger" style="display:none">
    <noscript>Javascript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
  </div>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :phone %>
    <%= f.text_field :phone, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_area :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/delivery_agencies/edit.html.erb
<h1>Editing Delivery Agency</h1>

<%= render 'form' %>

<%= link_to 'Show', @delivery_agency %> |
<%= link_to 'Back', delivery_agencies_path %>

app/views/delivery_agencies/index.html.erb
<h1>Delivery Agency</h1>

<%= form_tag destroy_multiple_delivery_agencies_path, method: :delete do %>
  <div class="form-group">
    <div class="btn-group">
      <%= link_to 'Add', new_delivery_agency_path, class: "btn btn-primary" %>
      <%= submit_tag "Delete", data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %>
    </div>
    <div class="right">
      <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="glyphicon glyphicon-print" aria-hidden="true"></span><span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li><a href="#">Print as List</a></li>
          <li><a href="#">Print as Summary</a></li>
        </ul>
      </div>

      <div class="btn-group">
        <div class="btn btn-group">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span><span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <li>-Per Page-</li>
            <li><%= link_to "2 per page", delivery_agencies_path(per_page: "2") %></li>
            <li><%= link_to "10 per page", delivery_agencies_path(per_page: "10") %></li>
            <li><%= link_to "20 per page", delivery_agencies_path(per_page: "20") %></li>
            <li><%= link_to "30 per page", delivery_agencies_path(per_page: "30") %></li>
            <li><%= link_to "40 per page", delivery_agencies_path(per_page: "40") %></li>
            <li><%= link_to "50 per page", delivery_agencies_path(per_page: "50") %></li>
            <li><%= link_to "75 per page", delivery_agencies_path(per_page: "75") %></li>
            <li><%= link_to "100 per page", delivery_agencies_path(per_page: "100") %></li>
            <li><%= link_to "200 per page", delivery_agencies_path(per_page: "200") %></li>
          </ul>
        </div>
        <div class="btn btn-group">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span><span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <li><a href="#">View as</a></li>
            <li><a href="#">Import Data</a></li>
            <li><a href="#">Export Data</a></li>
            <li><a href="#">Save Changes as New View</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <table class="table table-bordered table-striped center">
    <thead>
      <tr>
        <th class="center"></th>
        <th class="center">No.</th>
        <th class="center">Name</th>
        <th class="center">Email</th>
        <th class="center">Phone</th>
        <th class="center">Address</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @delivery_agencies.each_with_index do |delivery_agency, i| %>
        <tr>
          <td>
            <div class="form-group">
              <%= check_box_tag "delivery_agencies[]", delivery_agency.id %>
            </div>
          </td>
          <td><%= (i+1) %></td>
          <td><%= delivery_agency.name %></td>
          <td><%= delivery_agency.email %></td>
          <td><%= delivery_agency.phone %></td>
          <td><%= delivery_agency.address %></td>
          <td>
            <div class="btn-group">
              <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Select <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit', edit_delivery_agency_path(delivery_agency), class: "btn btn-link" %></li>
                <li><%= link_to 'Destroy', delivery_agency, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></li>
              </ul>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <div class="center">
    <div class="digg_pagination">
      <%= will_paginate @delivery_agencies %>
    </div>
  </div>
<% end %>

app/views/delivery_agencies/new.html.erb
<h1>New Delivery Agency</h1>

<%= render 'form' %>

<%= link_to 'Back', delivery_agencies_path %>

app/views/delivery_agencies/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @delivery_agency.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @delivery_agency.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @delivery_agency.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @delivery_agency.address %>
</p>

<%= link_to 'Edit', edit_delivery_agency_path(@delivery_agency) %> |
<%= link_to 'Back', delivery_agencies_path %>