config/routes.rb
Rails.application.routes.draw do

  get 'orders/add_product'

  get 'admin/permission'
  get 'admin/:id/edit' => 'admin#edit', :as => "admin_edit"
  patch 'admin/:id' => 'admin#update'
  put 'admin/:id' => 'admin#update'

  get 'orders/search_test'
  get 'orders/add_customer'

  resources :orders do
    collection do
      delete 'destroy_multiple'
      get 'search_action'
      get 'search_result'
      get 'sku_select'
    end
  end
  resources :delivery_agencies do
    collection do
      delete 'destroy_multiple'
    end
  end
  resources :business_groups do
    collection do
      delete 'destroy_multiple'
    end
  end
  resources :suppliers do
    collection do
      delete 'destroy_multiple'
    end
  end

  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }

  resources :products do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :customers do
      collection do
        delete 'destroy_multiple'
      end
    end

  devise_scope :user do
    root to: "devise/sessions#new"
  end

end

app/models/business_group.rb
class BusinessGroup < ActiveRecord::Base
end

app/controllers/business_groups_controller.rb
class BusinessGroupsController < ApplicationController
  require 'will_paginate/array'

  before_action :set_business_group, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /business_groups
  # GET /business_groups.json
  def index
    @business_groups = BusinessGroup.all
    @per_page = params[:per_page] || BusinessGroup.per_page || 2
    @business_groups = @business_groups.paginate( :per_page => @per_page, :page => params[:page])
  end

  # GET /business_groups/1
  # GET /business_groups/1.json
  def show
  end

  # GET /business_groups/new
  def new
    @business_group = BusinessGroup.new
  end

  # GET /business_groups/1/edit
  def edit
  end

  # POST /business_groups
  # POST /business_groups.json
  def create
    @business_group = BusinessGroup.new(business_group_params)

    respond_to do |format|
      if @business_group.save
        format.html { redirect_to @business_group, notice: 'Business group was successfully created.' }
        format.json { render :show, status: :created, location: @business_group }
      else
        format.html { render :new }
        format.json { render json: @business_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /business_groups/1
  # PATCH/PUT /business_groups/1.json
  def update
    respond_to do |format|
      if @business_group.update(business_group_params)
        format.html { redirect_to @business_group, notice: 'Business group was successfully updated.' }
        format.json { render :show, status: :ok, location: @business_group }
      else
        format.html { render :edit }
        format.json { render json: @business_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /business_groups/1
  # DELETE /business_groups/1.json
  def destroy
    @business_group.destroy
    respond_to do |format|
      format.html { redirect_to business_groups_url, notice: 'Business group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroy_multiple
    BusinessGroup.destroy(params[:business_groups])
    respond_to do |format|
      format.html {redirect_to business_groups_url, notice: 'Business groups were successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business_group
      @business_group = BusinessGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_group_params
      params.require(:business_group).permit(:name)
    end
end

app/helpers/business_groups_helper.rb
module BusinessGroupsHelper
end

app/views/business_groups/_form.html.erb
<%= form_for(@business_group) do |f| %>
  <% if @business_group.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4><%= pluralize(@business_group.errors.count, "error") %> prohibited this business group from being saved:</h4>

      <ul>
      <% @business_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="stripe_error" class="alert alert-danger" style="display:none">
    <noscript>Javascript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
  </div>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Sumit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/business_groups/edit.html.erb
<h1>Editing Business Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @business_group %> |
<%= link_to 'Back', business_groups_path %>

app/views/business_groups/index.html.erb
<h1>Business Group</h1>

<%= form_tag destroy_multiple_business_groups_path, method: :delete do %>
  <div class="form-group">
    <div class="btn-group">
      <%= link_to 'Add', new_business_group_path, class: "btn btn-primary" %>
      <%= submit_tag "Delete", data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %>
    </div>
    <div class="right">
      <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="glyphicon glyphicon-print" aria-hidden="true"></span><span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li><a href="#">Print as List</a></li>
          <li><a href="#">Print as Summary</a></li>
        </ul>
      </div>

      <div class="btn-group">
        <div class="btn btn-group">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span><span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <li>-Per Page-</li>
            <li><%= link_to "2 per page", business_groups_path(per_page: "2") %></li>
            <li><%= link_to "10 per page", business_groups_path(per_page: "10") %></li>
            <li><%= link_to "20 per page", business_groups_path(per_page: "20") %></li>
            <li><%= link_to "30 per page", business_groups_path(per_page: "30") %></li>
            <li><%= link_to "40 per page", business_groups_path(per_page: "40") %></li>
            <li><%= link_to "50 per page", business_groups_path(per_page: "50") %></li>
            <li><%= link_to "75 per page", business_groups_path(per_page: "75") %></li>
            <li><%= link_to "100 per page", business_groups_path(per_page: "100") %></li>
            <li><%= link_to "200 per page", business_groups_path(per_page: "200") %></li>
          </ul>
        </div>
        <div class="btn btn-group">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span><span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <li><a href="#">View as</a></li>
            <li><a href="#">Import Data</a></li>
            <li><a href="#">Export Data</a></li>
            <li><a href="#">Save Changes as New View</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <table class="table table-bordered table-striped center">
    <thead>
      <tr>
        <th class="center"></th>
        <th class="center">No.</th>
        <th class="center">Name</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @business_groups.each_with_index do |business_group, i| %>
        <tr>
          <td>
            <div class="form-group">
              <%= check_box_tag "business_groups[]", business_group.id %>
            </div>
          </td>
          <td><%= (i+1) %></td>
          <td><%= business_group.name %></td>
          <td>
            <div class="btn-group">
              <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Select <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit', edit_business_group_path(business_group), class: "btn btn-link" %></li>
                <li><%= link_to 'Destroy', business_group, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></li>
              </ul>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <div class="center">
    <div class="digg_pagination">
      <%= will_paginate @business_groups %>
    </div>
  </div>
<% end %>

app/views/business_groups/new.html.erb
<h1>New Business Group</h1>

<%= render 'form' %>

<%= link_to 'Back', business_groups_path %>

app/views/business_groups/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @business_group.name %>
</p>

<%= link_to 'Edit', edit_business_group_path(@business_group) %> |
<%= link_to 'Back', business_groups_path %>