config/routes.rb
Rails.application.routes.draw do

  get 'orders/add_product'

  get 'admin/permission'
  get 'admin/:id/edit' => 'admin#edit', :as => "admin_edit"
  patch 'admin/:id' => 'admin#update'
  put 'admin/:id' => 'admin#update'

  get 'orders/search_test'
  get 'orders/add_customer'

  resources :orders do
    collection do
      delete 'destroy_multiple'
      get 'search_action'
      get 'search_result'
      get 'sku_select'
    end
  end
  resources :delivery_agencies do
    collection do
      delete 'destroy_multiple'
    end
  end
  resources :business_groups do
    collection do
      delete 'destroy_multiple'
    end
  end
  resources :suppliers do
    collection do
      delete 'destroy_multiple'
    end
  end

  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }

  resources :products do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :customers do
      collection do
        delete 'destroy_multiple'
      end
    end

  devise_scope :user do
    root to: "devise/sessions#new"
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x" },  :default_url => ("default.jpg")
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	serialize :marketplace, Array

	belongs_to :user

	belongs_to :order, class_name: "Order"

	has_many :marketplaces, class_name: "Marketplace", foreign_key: "id"

	def self.search(search)
		where("product_code LIKE ?", "%#{search}%")
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  require 'will_paginate/array'

  # GET /products
  # GET /products.json
  def index
    if current_user && current_user.staff?
      @products = Product.where(user: current_user).order("created_at DESC")
    else
      @products = Product.all.order("created_at DESC")
    end
    #@products = Product.all
    @per_page = params[:per_page] || Product.per_page || 2
    @products = @products.paginate( :per_page => @per_page, :page => params[:page])
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @marketplaces = Marketplace.all
  end

  # GET /products/1/edit
  def edit
    @marketplaces = Marketplace.all

    #params['div_category'] = @product.category
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id

    @product.category = params[:product][:category]

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @product.modi_user_name = current_user.name
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroy_multiple
    Product.destroy(params[:products])
    respond_to do |format|
      format.html {redirect_to products_url, notice: 'Products were successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:business_group, :category, :supplier, :brand, :product_code, :price_cny, :price_krw, :stock, :variation, :color, :size, :weight, :dimension, :material_m, :material_e, :product_name, :description, :keyword, {:marketplace => []}, :status, :image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product, :html => { :multipart => true }) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h4>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="stripe_error" class="alert alert-danger" style="display:none">
    <noscript>Javascript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :business_group %> <font color="orange">*</font>
        <%= f.select(:business_group, options_from_collection_for_select(BusinessGroup.all,"name","name", f.object.business_group ), {},  {:class => "form-control"}) %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :category %>
    <div id="div_category">
      <%= "ff" %>
    </div>
    <% if @product %>
      <%= f.hidden_field :category, :value => @product.category %>
    <% else %>
      <%= f.hidden_field :category %>
    <% end %>
    <div class="row">
      <div class="col-md-5">
        <div class="col-md-4">
          <%= select_tag 'cat1', options_for_select([['-select-', ''], ['Hot','hot'], ['Cool', 'cool'], ['Hot & Cool']]), {class: "form-control"} %>
        </div>
        <div class="col-md-4">
          <%= select_tag 'cat2', options_for_select([['-select-', ''], ['Hot','hot'], ['Cool', 'cool']]), {class: "form-control"} %>
        </div>
        <div class="col-md-4">
          <%= select_tag 'cat3', options_for_select([['-select-', ''], ['Hot','hot'], ['Cool', 'cool']]), {class: "form-control"} %>
        </div>
      </div>
      <div class="col-md-7">
        <div class="col-md-3">
          <%= select_tag 'cat4', options_for_select([['-select-', ''], ['Hot','hot'], ['Cool', 'cool']]), {class: "form-control"} %>
        </div>
        <div class="col-md-3">
          <%= select_tag 'cat5', options_for_select([['-select-', ''], ['Hot','hot'], ['Cool', 'cool']]), {class: "form-control"} %>
        </div>
        <div class="col-md-3">
          <%= select_tag 'cat6', options_for_select([['-select-', ''], ['Hot','hot'], ['Cool', 'cool']]), {class: "form-control"} %>
        </div>
        <div class="col-md-3">
          <%= select_tag 'cat7', options_for_select([['-select-', ''], ['Hot','hot'], ['Cool', 'cool']]), {class: "form-control"} %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :product_code %> <font color="orange">*</font>
        <%= f.text_field :product_code, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :supplier %> <font color="orange">*</font>
        <%= f.select(:supplier, options_from_collection_for_select(Supplier.all,"company_name","company_name", f.object.supplier), {},  {:class => "form-control"}) %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :brand %>
        <%= f.text_field :brand, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :stock %> <font color="orange">*</font>
        <%= f.text_field :stock, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-5">
      <div class="form-group">
        <%= f.label :price_cny, "Price" %> <font color="orange">*</font>
        <%= f.text_field :price_cny, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-1">
      <div class="form-group">
        <p><br><font color="#CCC"><%= content_tag( :div, 'CNY' ) %></font></p>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :variation %> <font color="orange">*</font>
        <%= f.select(:variation, options_for_select([['None','none'],['Size','size'],['Color','color'],['Size & Color', 'size_and_color']], :selected => f.object.variation), {}, {:onChange => "_variation()",class: "form-control variation"}) %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-5">
      <div class="form-group">
        <%= f.label :price_krw, "Price" %>
        <%= f.text_field :price_krw, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-1">
      <div class="form-group">
        <p><br><font color="#CCC"><%= content_tag( :div, 'KRW' ) %></font></p>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group size" style="display:none">
        <%= f.label :size %>
        <%= f.text_field :size, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-5">
      <div class="form-group">
        <%= f.label :weight %> <font color="orange">*</font>
        <%= f.text_field :weight, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-1">
    </div>
    <div class="col-md-6">
      <div class="form-group color" style="display:none">
        <%= f.label :color %>
        <%= f.select(:color, options_for_select([['Black','black'],['White','white'],['Brown','brown'],['Beige','beige'],['Blue','blue'],['Red','red'],['Multicolored','multicolored'],['Other','other']]), {}, {class: "form-control"}) %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :dimension %> <font color="orange">*</font>
        <%= f.text_area :dimension, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :image, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :material_m %> <font color="orange">*</font>
        <%= f.text_area :material_m, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :marketplace %><br>
          <% for market in @marketplaces %>
            <%= f.check_box(:marketplace, { :multiple => true, :checked => (@product.marketplace.include?(market.name)) }, market.name, nil) %>
            <%= market.name %>
          <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :material_e %>
        <%= f.text_area :material_e, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :status %>
        <%= f.select(:status, options_for_select([['Active','Active'],['Inactive','Inactive']], :selected => f.object.status), {}, {class: "form-control"}) %>
      </div>
    </div>
  </div>
  
  <div class="form-group center">
    <input type="button" class="btn btn-primary btn_more" onclick="more()" value="More"  />
    <input type="button" class="btn btn-default btn_hide" onclick="hide()" value="Hide"style="display:none"  />
  </div>

  <div class="more_hide" style="display:none">
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :product_name %>
          <%= f.text_field :product_name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :keyword %>
          <%= f.text_area :keyword, class: "form-control" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product, class: "btn btn-link" %> |
<%= link_to 'Back', products_path, class: "btn btn-link" %>

app/views/products/index.html.erb
<h1>All Products</h1>

<%= form_tag destroy_multiple_products_path, method: :delete do %>
  <div class="form-group">
    <div class="btn-group">
      <%= link_to 'Add', new_product_path, class: "btn btn-primary" %>
      <%= submit_tag "Delete", data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %>
    </div>
    <div class="right">
      <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="glyphicon glyphicon-print" aria-hidden="true"></span><span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li><a href="#">Print as List</a></li>
          <li><a href="#">Print as Summary</a></li>
        </ul>
      </div>

      <div class="btn-group">
        <div class="btn btn-group">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span><span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <li>-Per Page-</li>
            <li><%= link_to "2 per page", products_path(per_page: "2") %></li>
            <li><%= link_to "10 per page", products_path(per_page: "10") %></li>
            <li><%= link_to "20 per page", products_path(per_page: "20") %></li>
            <li><%= link_to "30 per page", products_path(per_page: "30") %></li>
            <li><%= link_to "40 per page", products_path(per_page: "40") %></li>
            <li><%= link_to "50 per page", products_path(per_page: "50") %></li>
            <li><%= link_to "75 per page", products_path(per_page: "75") %></li>
            <li><%= link_to "100 per page", products_path(per_page: "100") %></li>
            <li><%= link_to "200 per page", products_path(per_page: "200") %></li>
          </ul>
        </div>
        <div class="btn btn-group">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span><span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <li><a href="#">View as</a></li>
            <li><a href="#">Import Data</a></li>
            <li><a href="#">Export Data</a></li>
            <li><a href="#">Save Changes as New View</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <table class="table table-bordered table-striped center">
    <thead>
      <tr>
        <th class="center"></th>
        <th class="center">No.</th>
        <th class="center">Product Code</th>
        <th class="center">Image</th>
        <th class="center">Price</th>
        <th class="center">Status</th>
        <th class="center">Business Group</th>
        <th class="center">Category</th>
        <th class="center">Stock</th>
        <th class="center">Marketplaces</th>
        <th class="center">Added Time</th>
        <th class="center">Added user</th>
        <th class="center">Modified Time</th>
        <th class="center">Modified User</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @products.each_with_index do |product, i| %>
        <tr>
          <td>
            <div class="form-group">
              <%= check_box_tag "products[]", product.id %>
            </div>
          </td>
          <td><%= (i+1) %></td>
          <td><%= product.product_code %></td>
          <td><%= image_tag product.image.url(:thumb) %></td>
          <td><%= product.price_cny %></td>
          <td><%= product.status %></td>
          <td><%= product.business_group %></td>
          <td><%= product.category %></td>
          <td><%= product.stock %></td>
          <td>
            <% for j in 0..(product.marketplace.count-1) do %>
              <% if j == 0 %>
                <%= product.marketplace[0] %>
              <% else %>
                , <%= product.marketplace[j] %>
              <% end %>
            <% end %>
          </td>
          <td><%= product.created_at %></td>
          <td><%= product.user.name %></td>
          <td><%= product.updated_at %></td>
          <td><%= product.modi_user_name %></td>
          <td>
            <div class="btn-group">
              <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Select <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit', edit_product_path(product), class: "btn btn-link" %></li>
                <li><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></li>
              </ul>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <div class="center">
    <div class="digg_pagination">
      <%= will_paginate @products %>
    </div>
  </div>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path, class: "btn btn-link" %>

app/views/products/show.html.erb
<p>
  <strong>Business group:</strong>
  <%= @product.business_group %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category %>
</p>

<p>
  <strong>Supplier:</strong>
  <%= @product.supplier %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand %>
</p>

<p>
  <strong>Product code:</strong>
  <%= @product.product_code %>
</p>

<p>
  <strong>Price cny:</strong>
  <%= @product.price_cny %>
</p>

<p>
  <strong>Price krw:</strong>
  <%= @product.price_krw %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @product.stock %>
</p>

<p>
  <strong>Variation:</strong>
  <%= @product.variation %>
</p>

<p>
  <strong>Color:</strong>
  <%= @product.color %>
</p>

<p>
  <strong>Size:</strong>
  <%= @product.size %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @product.weight %>
</p>

<p>
  <strong>Dimension:</strong>
  <%= @product.dimension %>
</p>

<p>
  <strong>Material m:</strong>
  <%= @product.material_m %>
</p>

<p>
  <strong>Material e:</strong>
  <%= @product.material_e %>
</p>

<p>
  <strong>Product name:</strong>
  <%= @product.product_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Keyword:</strong>
  <%= @product.keyword %>
</p>

<p>
  <strong>Marketplace:</strong>
  <%= @product.marketplace %>
</p>

<p>
  <strong>Status:</strong>
  <%= @product.status %>
</p>

<%= link_to 'Edit', edit_product_path(@product), class: "btn btn-link" %> |
<%= link_to 'Back', products_path, class: "btn btn-link" %>