config/routes.rb
Rails.application.routes.draw do

  get 'orders/add_product'

  get 'admin/permission'
  get 'admin/:id/edit' => 'admin#edit', :as => "admin_edit"
  patch 'admin/:id' => 'admin#update'
  put 'admin/:id' => 'admin#update'

  get 'orders/search_test'
  get 'orders/add_customer'

  resources :orders do
    collection do
      delete 'destroy_multiple'
      get 'search_action'
      get 'search_result'
      get 'sku_select'
    end
  end
  resources :delivery_agencies do
    collection do
      delete 'destroy_multiple'
    end
  end
  resources :business_groups do
    collection do
      delete 'destroy_multiple'
    end
  end
  resources :suppliers do
    collection do
      delete 'destroy_multiple'
    end
  end

  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }

  resources :products do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :customers do
      collection do
        delete 'destroy_multiple'
      end
    end

  devise_scope :user do
    root to: "devise/sessions#new"
  end

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/products">Becomeus</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav nav-pills">
        <li><a data-toggle="tab" href="#product">Products</a></li>
        <li><a data-toggle="tab" href="#order">Orders</a></li>
        <li><a href="#">Purchases</a></li>
        <li><a data-toggle="tab" href="#customer">Customers</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <% if current_user.admin == true %>
            <li><%= link_to 'Permission', admin_permission_path %></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><a href="/users/sign_up">Sign Up</a></li>
          <li><a href="/users/sign_in">Sign In</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="tab-content container">
  <div class="tab-pane active" id="product">
    <ul class="nav navbar-nav">
      <li><%= link_to 'All Products', products_path %></li>
      <li><%= link_to 'New Product', new_product_path %></li>
      <li><%= link_to 'Suppliers', suppliers_path%></li>
      <li><%= link_to 'All Products(Export)'%></li>
      <li><%= link_to 'Business Group', business_groups_path %></li>
    </ul>
  </div>
  <div class="tab-pane" id="order">
    <ul class="nav navbar-nav">
      <li><%= link_to 'All Orders', orders_path %></li>
      <li><%= link_to 'New Order', new_order_path %></li>
      <li><%= link_to 'Pending', orders_search_test_path%></li>
      <li><%= link_to 'Delivery Pending'%></li>
      <li><%= link_to 'Delivery Agency', delivery_agencies_path %></li>
    </ul>
  </div>
  <div class="tab-pane" id="customer">
    <ul class="nav navbar-nav">
      <li><%= link_to 'All Customers', customers_path %></li>
      <li><%= link_to 'New Customer', new_customer_path %></li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Becomeus</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <style type="text/css"><%= yield :stylesheets %></style>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="header_id">
   <%= render 'layouts/header' %>
</div>

<div class="container">
	<% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
          <div class="alert alert-<%= name.to_s == 'notice' ? "success" : "danger" %> alert-dismissable">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <%= content_tag :div, msg, :id => "flash_#{name}" %>
          </div>
        <% end %>
    <% end %>
	
	<%= yield %>
</div>

</body>
</html>